# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release 
      
    - name: Zip output
      run: zip -r ${{ github.event.repository.name }}.zip ./LostArkAuctionHelper/bin/Release/net6.0-windows

    - name: Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: "latest"
        # Should this release be marked as a draft?
        draft: false
        # Should this release be marked as a pre-release?
        prerelease: false
        # Release title (for automatic releases)
        title: LostArk Auction Helper
        # Assets to upload to the release
        files: ${{ github.event.repository.name }}.zip
